### ISSUE TITLE
Filtering by subscription name doesn't work when using `_id` in a selector

### ISSUE THREAD

**Issue by artahian** [percolatestudio/find-from-publication#6]
Here is my case:
I am subscribed to my own user from `db.users` collection.
Then I am subscribing to the list of users on some page filtered by user id's, i.e. something like:

```
db.users.find({_id: {$in: ['myuserid', 'otheruserid1', 'otheruserid2', ...]}}, {skip: 10})
```

after this 

```
db.users.findFromPublication('mysub', {_id: {$in: ['myuserid', 'otheruserid1', 'otheruserid2', ...]}})
```

always includes my user even though it is not received from `mysub`, but is subscribed to separately. When I remove the `_id` filter, i.e. doing just

```
db.users.findFromPublication('mysub', {})
```

it returns LESS elements (same list excluding me) even though removing a filter is not expected to exclude any results.

**Comment by sebakerckhof** [comment]
Thgis has been fixed in version 0.2.0
